### ISSUE TITLE
Couldn't find chia_plot in your PATH.

### ISSUE THREAD

**Issue by stikmou007** [tobernguyen/madmax-manager#4]
Hi,
I don't have find the way to start th manager.
after the git clone and the configuration of config.ini, it say "Couldn't find chia_plot in your PATH."
Can you explain me what to do?
The "chia_plot" was on the madmax folder. How to set it?

Regards,

**Comment by tobernguyen** [comment]
How did you install madmax chia plotter?

**Comment by stikmou007** [comment]
I have following the ubuntu installation step on the git page https://github.com/madMAx43v3r/chia-plotter

**Comment by stikmou007** [comment]
Ok I have found. On Linux, the madmax path wasn't set on the $PATH linux .
I have add it and now it's works 

For who don't know, you need to use this command:
export PATH=$PATH:/place/with/the/file

Sorry ;)

**Comment by ozgurcb** [comment]
> Ok I have found. On Linux, the madmax path wasn't set on the $PATH linux .
> I have add it and now it's works
> 
> For who don't know, you need to use this command:
> export PATH=$PATH:/place/with/the/file
> 
> Sorry ;)

Can you please explain little bit clear. How to use that command ? Need explanation for dummies :/ Step by step maybe ? Sorry I'm really new to ubuntu and this commands.

**Comment by mrph28** [comment]
> Can you please explain little bit clear. How to use that command ? Need explanation for dummies :/ Step by step maybe ? Sorry I'm really new to ubuntu and this commands.

Just open Terminal, paste `export PATH=$PATH:` and then type the path to YOUR madmax binary folder.
Example: `export PATH=$PATH:/home/Downloads/chia-plotter/build`
