### ISSUE TITLE
pool_public_key missing

### ISSUE THREAD

**Issue by kata32** [tobernguyen/madmax-manager#5]
When I start plotting I get 
"Missing value for pool_public_key. Please set it in config.ini file."
but it is normal that I do not specify the pool_public_key when I plot for a pool, instead I have to use the pool_contract_address

**Comment by tobernguyen** [comment]
Thanks for reporting this. I will fix this soon.

**Comment by tobernguyen** [comment]
@kata32 I have removed the requirement of `pool_public_key` for now. It should work for you. Please pull the latest code and try again.

**Comment by tobernguyen** [comment]
Close for now as it has been resolved. Feel free to re-open if you still have the issue.
